import { HttpClient } from '@angular/common/http';
import { Injectable, inject } from '@angular/core';
import type { Observable } from 'rxjs';

import type { RegionalForecastDocument } from '../models/regional-forecast';

/**
 * Loads the JSON forecast artifact generated by the backend pipeline.
 */
@Injectable({ providedIn: 'root' })
export class ForecastDataService {
  private readonly httpClient = inject(HttpClient);

  /**
   * Fetches the latest forecast document from the public data directory.
   */
  loadRegionalForecast(): Observable<RegionalForecastDocument> {
    return this.httpClient.get<RegionalForecastDocument>('/data/new-england-forecast-sample.json');
  }
}

